name: Python Application Test with Github Actions 
on:
  schedule:
  - cron:  '0 3 * * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
          
      - name: install packages and dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: test with pytest
        run: |
          make test
      - name: format
        run: |
          make format
      - name: deploy
        run: |
          make deploy
